// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaJpLsDWKP3UN_oDGNWeECuWIvZdG7WM',
    appId: '1:723623920177:web:e8f76b31f9562b7849cb10',
    messagingSenderId: '723623920177',
    projectId: 'ground-water-management-932be',
    authDomain: 'ground-water-management-932be.firebaseapp.com',
    storageBucket: 'ground-water-management-932be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Os0NX2TKHjynTCF0UvVUFExFXL8aQ9U',
    appId: '1:723623920177:android:47ebe3ece8243f8d49cb10',
    messagingSenderId: '723623920177',
    projectId: 'ground-water-management-932be',
    storageBucket: 'ground-water-management-932be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZ9VIiipkZFT1EjRKiVShvs9GiAf7oTo',
    appId: '1:723623920177:ios:881adb9c5463d44e49cb10',
    messagingSenderId: '723623920177',
    projectId: 'ground-water-management-932be',
    storageBucket: 'ground-water-management-932be.firebasestorage.app',
    iosBundleId: 'com.example.uicomponentsforgwm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlZ9VIiipkZFT1EjRKiVShvs9GiAf7oTo',
    appId: '1:723623920177:ios:881adb9c5463d44e49cb10',
    messagingSenderId: '723623920177',
    projectId: 'ground-water-management-932be',
    storageBucket: 'ground-water-management-932be.firebasestorage.app',
    iosBundleId: 'com.example.uicomponentsforgwm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRaJpLsDWKP3UN_oDGNWeECuWIvZdG7WM',
    appId: '1:723623920177:web:2ce75104a036eacc49cb10',
    messagingSenderId: '723623920177',
    projectId: 'ground-water-management-932be',
    authDomain: 'ground-water-management-932be.firebaseapp.com',
    storageBucket: 'ground-water-management-932be.firebasestorage.app',
  );
}
